---
mail_relay_networks:
  - 127.0.0.0/8
  - 172.25.250.0/24

project_domain: nexcore.local

timezone: Europe/Zagreb

common_packages:
  - vim
  - bash-completion
  - wget
  - tar
  - firewalld

managed_accounts:
  - username: ops01
    groups:
      - ops
      - wheel
    sudo: true

  - username: dev01
    groups:
      - dev
    sudo: false

  - username: dev02
    groups:
      - dev
    sudo: false

  - username: mkt01
    groups:
      - marketing
    sudo: false

ssh_allowed_group: wheel

web_root: /var/www

nfs_mount_point: /mnt/nexcore_share

dns_forwarder: 8.8.8.8

wordpress_database:
  name: wordpress
  user: wordpress
  password: wordpresspass123
  host: serverb

mediawiki_database:
  name: mediawiki
  user: mediawiki
  password: mediawikipass123
  host: serverb
