---
project_domain: nexcore.local

timezone: Europe/Zagreb

common_packages:
  - vim
  - bash-completion
  - wget
  - tar
  - firewalld

managed_accounts:
  - username: ops01
    groups:
      - ops
      - wheel
    sudo: true

  - username: dev01
    groups:
      - dev
    sudo: false

  - username: dev02
    groups:
      - dev
    sudo: false

  - username: mkt01
    groups:
      - marketing
    sudo: false

ssh_allowed_group: wheel

web_root: /var/www

nfs_mount_point: /mnt/nexcore_share

dns_forwarder: 8.8.8.8
