---
- name: Base system configuration
  hosts: managed
  become: true

  roles:
    - role: users
      tags: users

    - role: security
      tags: security

    - role: patching
      tags: patching

    - role: logging
      tags: logging

- name: Configure storage services
  hosts: serverb
  become: true

  roles:
    - role: storage
      tags: storage

- name: Configure NFS and automount services
  hosts: managed
  become: true

  roles:
    - role: automount
      tags: automount

- name: Configure database services
  hosts: db
  become: true

  roles:
    - role: database
      tags: database

    - role: backup
      tags: backup

- name: Configure DNS, web and email services
  hosts: servera
  become: true

  roles:
    - role: dns
      tags: dns

    - role: web
      tags: web

    - role: email
      tags: email
