---
health_log_file: /var/log/nexcore-health.log

health_script_path: /usr/local/bin/nexcore-health-check.sh

health_check_hour: 3

automatic_updates_package: dnf-automatic

automatic_updates_apply: true
